### ISSUE TITLE
Error. What Node version should this be ran at? What are the other dependencies versions? Thanks.

### ISSUE THREAD

**Issue by Realsupersaiyan** [JamesKyburz/youtube-audio-stream#107]
` throw er; // Unhandled 'error' event
^

TypeError: Invalid non-string/buffer chunk
at validChunk (_stream_writable.js:238:10)
at PassThrough.Writable.write (_stream_writable.js:272:21)
at PassThrough.Writable.end (_stream_writable.js:536:10)
at emitThree (events.js:140:20)
at DestroyableTransform.emit (events.js:216:7)
at emitThree (events.js:135:13)
at FfmpegCommand.emit (events.js:216:7)
at emitEnd (C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\li
b\processor.js:424:16)
at C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\lib\process
or.js:433:16
at C:\Users\Matt\code\project-discord\node_modules\async\dist\async.js:421:1
6

**Comment by linktothapast** [comment]
Getting similar issues all of a sudden.

**Comment by Realsupersaiyan** [comment]
Hey there. MAKE SURE that you've installed FFPMEG on your system. My project also NEEDED the ffmpeg-binaries module from npm installed on what I was working on as well. Hope this helps!

**Comment by JamesKyburz** [comment]
If you are getting issues locally you can try testing the docker image.
