### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lims4010** [JamesKyburz/youtube-audio-stream#118]
It seems like I am running into similar errors seen previously after trying to pipe the audio stream.

RangeError: Maximum call stack size exceeded
    at PassThrough.output.on.error (...\Documents\Project\node_modules\youtube-audio-stream\index.js:36:13)
    at PassThrough.emit (events.js:182:13).....

I've also ran the module with the most recent dependencies as well (ytdl-core 0.29.7). Trying to understand what's going on but I'm hitting a wall. What is the issue?

**Comment by lims4010** [comment]
Solved my own issue. Had to add ffmpeg to PATH otherwise dependencies i.e. ytdl-core will not work. Sorry about the quick to post but hopefully someone else is helped by this info!
